In [2]:
#Write a Python script that opens a file in read mode and prints its contents. 
#You can use any text file for practice
import csv

with open('Desktop/tdi/python/week 3/practice.txt', 'r') as prac:
    print(prac.read())

Hello world
I am a text file
What do you want to know about me?


In [3]:
#Create a Python script that writes the string "Hello, Data Analysis!" to a new text file.
import csv

with open('Desktop/tdi/python/week 3/practice2.txt', 'w') as prac2:
    prac2.write('Hello, Data Analysis!')

In [1]:
#Use the “csv” module to read the Titanic dataset. Print the first 5 rows of the dataset.

import numpy as np
import csv

with open('Desktop/tdi/python/week 3/titanic.csv', 'r') as titanic:
    reader = csv.reader(titanic)
    header_row = next(reader)
    data = list(reader)

titanic_array = np.array(data)

column_index = 8
empty_strings = titanic_array[:, column_index] == ''

titanic_array[empty_strings, column_index] = 0

for rows in titanic_array[:5]:
    print(rows)

['1' '1' 'Allen, Miss. Elisabeth Walton' 'female' '29' '0' '0' '24160'
 '211.3375' 'B5' 'S' '2' '' 'St Louis, MO']
['1' '1' 'Allison, Master. Hudson Trevor' 'male' '0.9167' '1' '2' '113781'
 '151.55' 'C22 C26' 'S' '11' '' 'Montreal, PQ / Chesterville, ON']
['1' '0' 'Allison, Miss. Helen Loraine' 'female' '2' '1' '2' '113781'
 '151.55' 'C22 C26' 'S' '' '' 'Montreal, PQ / Chesterville, ON']
['1' '0' 'Allison, Mr. Hudson Joshua Creighton' 'male' '30' '1' '2'
 '113781' '151.55' 'C22 C26' 'S' '' '135'
 'Montreal, PQ / Chesterville, ON']
['1' '0' 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)' 'female' '25'
 '1' '2' '113781' '151.55' 'C22 C26' 'S' '' ''
 'Montreal, PQ / Chesterville, ON']


In [5]:
#After reading the Titanic CSV file, count the total number of passengers.

count_passengers = len(titanic_array)

print(f'The number of passengers on the titanic is {count_passengers}')

The number of passengers on the titanic is 1309


In [3]:
#Write a script that calculates the average fare paid by passengers. Use the Titanic CSV data for this calculation.
i = 0
sum = 0
count = 0
while i < 1309:
    if titanic_array[i, 8] == '':
        pass
    else:
        count += 1
        sum += float(titanic_array[i, 8])
        i += 1

average_fare = sum / count

print(f'The average transport fare = {round(average_fare, 2)}')

The average transport fare = 33.27


In [4]:
#Write a Python script that calculates the number of survivors per passenger class (1st, 2nd, and 3rd class)

passenger_class = np.unique(titanic_array[:, 0])

survivor_per_class = {}

for pclass in passenger_class:
    class_rows = titanic_array[titanic_array[:,0] == pclass]
    survivors = np.sum(class_rows[:, 1].astype(int))
    survivor_per_class[pclass] = survivors

for pclass, survivors in survivor_per_class.items():
    print(f'Passengers class {pclass} : {survivors} survivors')

Passengers class 1 : 200 survivors
Passengers class 2 : 119 survivors
Passengers class 3 : 181 survivors


In [10]:
#Import the NumPy library and create a 1D array containing the following numbers: “[10, 15, 20, 25]”. Print the array
import numpy as np

data = [10, 15, 20, 25]

np_data = np.array(data)
np_data

array([10, 15, 20, 25])

In [14]:
#Multiply each element by 2

np_data_multiplied = np_data * 2
np_data_multiplied

array([20, 30, 40, 50])

In [15]:
#Subtract 5 from each element.

np_data_subtracted = np_data - 5
np_data_subtracted

array([ 5, 10, 15, 20])

In [14]:
#Create a 2D NumPy array with shape (3, 3) using the following data: 

d_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

np_2d_data = np.array(d_data)
np_2d_data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# The mean fare

mean_fare = np.mean(titanic_array[:,8].astype(float))

print(f'The mean fare is {round(mean_fare, 2)}')

The mean fare is 33.27


In [25]:
#The maximum fare

maximum_fare = np.max(titanic_array[:, 8].astype(float))

print(f'The maximum fare is {round(maximum_fare, 2)}')

The maximum fare is 512.33


In [27]:
#The minimum fare

minimum_fare = np.min(titanic_array[:, 8].astype(float))

print(f'The minimum fare is {round(minimum_fare, 2)}')

The minimum fare is 0.0


In [15]:
#Use array indexing to extract the first row and first column of the 2D array created earlier. Print the results.

extracted_row_data = np_2d_data[0, :]
extracted_column_data = np_2d_data[:, 0]
print(f'First Row: {extracted_row_data}')
print(f'First Column: {extracted_column_data}')

First Row: [1 2 3]
First Column: [1 4 7]


In [35]:
#Create a NumPy array with 10 random numbers between 0 and 1. Print the array and find the maximum value
i = 0
random_num = []
while i < 10:
    random_num.insert(i, round(np.random.rand(), 2))
    i += 1

max_number =  np.max(random_num)
print(f'The maximum number is {max_number}')

The maximum number is 0.98


In [17]:
#1 Use the Titanic dataset and convert the "Survived" column to a NumPy array.
#2 Calculate the percentage of passengers who survived

survived_column_array = titanic_array[:, 1].astype(int)
i = 0
survived_count = 0
count = 0

while i < len(survived_column_array):
    if survived_column_array[i] == 1:
        survived_count += 1
        i += 1
    else:
        count += 1
        i += 1

survivors_percentage = (survived_count/(count + survived_count)) * 100

print(f'The percentage of survivors is {round(survivors_percentage, 2)}%')

The percentage of survivors is 38.2%
